version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: samuelantonio512/glpi:10.0.10
    container_name : glpi
    hostname: glpi
    ports:
      - "8080:80"
    volumes:
      - /var/www/html/glpi/:/var/www/html/glpi
      - ./apache_logs:/var/log/apache2
    restart: always
    
